### ISSUE TITLE
Crashes on NFC read

### ISSUE THREAD

**Issue by pimpimmi** [vicktor/FreeStyleLibre-NFC-Reader#6]
D/socialdiabetes( 5420): Tag ID: [B@1d1ca11
D/socialdiabetes( 5420): ---------------------------------------------------------------
D/socialdiabetes( 5420): nfcvTag ID: 0
D/socialdiabetes( 5420): getMaxTransceiveLength: 253
E/AndroidRuntime( 5420): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 5420): Process: com.socialdiabetes.freestylelibre, PID: 5420
E/AndroidRuntime( 5420): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 5420): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
E/AndroidRuntime( 5420): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 5420): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 5420): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 5420): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 5420): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5420): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5420): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 5420): Caused by: java.lang.IllegalArgumentException
E/AndroidRuntime( 5420): 	at java.util.Arrays.copyOfRange(Arrays.java:2663)
E/AndroidRuntime( 5420): 	at com.socialdiabetes.freestylelibre.Abbott$NfcVReaderTask.doInBackground(Abbott.java:214)
E/AndroidRuntime( 5420): 	at com.socialdiabetes.freestylelibre.Abbott$NfcVReaderTask.doInBackground(Abbott.java:161)
E/AndroidRuntime( 5420): 	at android.os.AsyncTask$2.call(AsyncTask.java:297)
E/AndroidRuntime( 5420): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 5420): 	... 4 more

**Comment by michcioh** [comment]
Hi, I've got the same problem. Any resolved ideas?

**Comment by chenmingqiang** [comment]
I also have the same problem, Any one resolved it?
